M48
; DRILL file {KiCad 9.0.2+dfsg-1} date 2026-10-08T02:08:59+0800
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2026-10-08T02:08:59+08:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,9.0.2+dfsg-1
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.650
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.900
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T3C1.800
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T4C2.200
%
G90
G05
T1
X97.11Y-61.0
X102.89Y-61.0
T2
X129.5Y-58.985
X132.5Y-58.985
T3
X79.5Y-89.0
X79.5Y-99.0
T4
X60.0Y-76.0
X62.0Y-134.0
X128.0Y-112.0
X142.0Y-88.0
M30
