import uuid, math
from sexp import *
from design import parts
U = lambda: Q(str(uuid.uuid4()))
NS = uuid.UUID("6b1f0c2e-0000-4000-8000-00000000c0de")
uid = lambda s: Q(str(uuid.uuid5(NS, s)))
ROOT = uid("root")
libsyms = {}; items = []
FLAGS = ["GND", "VBUS", "VSYS", "VBAT_SW"]
allparts = list(parts) + [dict(ref=f"#FLG0{i+1}", sym="power:PWR_FLAG", fp="", value="PWR_FLAG", lcsc="", pins={"1":n}, pos=None) for i,n in enumerate(FLAGS)]
# grid placement
x0, y0 = 30.48, 30.48; cx, cy = x0, y0; rowh = 0
order = sorted(allparts, key=lambda p: (p["ref"][0]!="U", p["ref"].startswith("#"), p["ref"]))
sheet_w = 400
def snap(v): return round(v/1.27)*1.27
for p in order:
    lib, name = p["sym"].split(":")
    s = get_symbol(lib, name)
    if p["sym"] not in libsyms:
        ls = ['symbol', Q(p["sym"])] + s[2:]
        libsyms[p["sym"]] = ls
    pl = pins(s)
    xs = [q["x"] for q in pl] + [0]; ys = [q["y"] for q in pl] + [0]
    w = max(xs)-min(xs)+30; h = max(ys)-min(ys)+16
    if cx + w > sheet_w: cx = x0; cy += rowh; rowh = 0
    sx, sy = snap(cx - min(xs) + 12), snap(cy + max(ys) + 6)
    cx += w; rowh = max(rowh, h)
    props = [['property', Q("Reference"), Q(p["ref"]), ['at', sx, sy - max(ys) - 3, 0], ['effects', ['font', ['size', 1.27, 1.27]]]],
             ['property', Q("Value"), Q(p["value"]), ['at', sx, sy - min(ys) + 3, 0], ['effects', ['font', ['size', 1.27, 1.27]]]],
             ['property', Q("Footprint"), Q(p["fp"]), ['at', sx, sy, 0], ['effects', ['font', ['size', 1.27, 1.27]], 'hide']],
             ['property', Q("Datasheet"), Q(""), ['at', sx, sy, 0], ['effects', ['font', ['size', 1.27, 1.27]], 'hide']],
             ['property', Q("LCSC"), Q(p["lcsc"]), ['at', sx, sy, 0], ['effects', ['font', ['size', 1.27, 1.27]], 'hide']]]
    sym = ['symbol', ['lib_id', Q(p["sym"])], ['at', sx, sy, 0], ['unit', 1], ['exclude_from_sim', 'no'],
           ['in_bom', 'no' if p["ref"].startswith("#") else 'yes'], ['on_board', 'no' if p["ref"].startswith("#") else 'yes'],
           ['dnp', 'no'], ['uuid', uid(p["ref"])]] + props
    seen = set()
    for q in pl:
        if q["num"] in seen: continue
        seen.add(q["num"]); sym.append(['pin', Q(q["num"]), ['uuid', U()]])
    sym.append(['instances', ['project', Q("creative-controller"), ['path', Q("/" + ROOT), ['reference', Q(p["ref"])], ['unit', 1]]]])
    items.append(sym)
    for q in pl:
        px, py = sx + q["x"], sy - q["y"]
        net = p["pins"].get(q["num"])
        if q["type"] == "no_connect" and net is None: continue
        if net is None or net.startswith("NC"):
            items.append(['no_connect', ['at', px, py], ['uuid', U()]]); continue
        ang = {0: 180, 180: 0, 90: 270, 270: 90}[int(q["rot"]) % 360]
        just = 'right' if ang in (180, 90) else 'left'
        items.append(['label', Q(net), ['at', px, py, ang], ['fields_autoplaced', 'yes'],
                      ['effects', ['font', ['size', 1.0, 1.0]], ['justify', just, 'bottom']], ['uuid', U()]])
sch = ['kicad_sch', ['version', 20231120], ['generator', Q("eeschema")], ['generator_version', Q("8.0")],
       ['uuid', ROOT], ['paper', Q("A3")],
       ['title_block', ['title', Q("CreativeDial main board")], ['rev', Q("A")], ['company', Q("generated by gen_sch.py")],
        ['comment', 1, Q("Net labels at every pin; nets defined in design.py")]],
       ['lib_symbols'] + list(libsyms.values())] + items + [['sheet_instances', ['path', Q("/"), ['page', Q("1")]]]]
open("creative-controller.kicad_sch", "w").write(dump(sch) + "\n")
print("symbols:", len(order), "y-extent", cy + rowh)
